name: Build and Push App Image

on:
  workflow_run:
    workflows: ["Build and Push Base Image"]
    types:
      - completed
  push:
    branches:
      - master
    paths-ignore:
      - 'Dockerfile.base'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push app image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ssl-cert-generator:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ssl-cert-generator:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/ssl-cert-generator:latest
            ghcr.io/${{ github.repository_owner }}/ssl-cert-generator:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/ssl-cert-generator-base:latest
          cache-to: type=inline