name: Docker Build and Push

on:
  push:
    branches: [ "master" ]  # 触发器，当推送到main分支时
  pull_request:
    branches: [ "master" ]  # 也可以在PR时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')"

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/ssl-cert-generator:latest
          ghcr.io/${{ github.repository_owner }}/ssl-cert-generator:${{ steps.date.outputs.date }}
          ${{ secrets.DOCKERHUB_USERNAME }}/ssl-cert-generator:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/ssl-cert-generator:${{ steps.date.outputs.date }}